application: phonic-monolith-841
version: 1
runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: endpoints
  version: 1.0

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: api.APPLICATION

- url: /static
  static_dir: static
- url: /fonts
  static_dir: fonts
- url: /.*
  script: main.application

builtins:
- remote_api: on

skip_files:
# These are App Engine's default values.
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# These are needed in development but aren't used in production.
- ^(.*/)?node_modules$
- ^(.*/)?package\.json$
